### ISSUE TITLE
relations plugin

### ISSUE THREAD

**Issue by mesemus** [oarepo/oarepo-model-builder-relations#1]
## Tasks

- [x] pinned main
- [x] tests
- [x] release
- [x] readme documentation
- [x] dev documentation

## Parts

- [x] relation to external document
    - [x] ingested:
        - [x] property
        - [x] array item
        - [x] property inside array
        - [x] array inside array
        - [x] custom field
- [x] intra-record relation
    - [x] ingested:
        - [x] property
        - [x] array item
        - [x] property inside array
        - [x] array inside array
        - [x] custom field

## Required for

- [x] NR
- [x] MOSBRI

**Comment by mirekys** [comment]
@mesemus can this issue be closed?
